language: bash
services: docker
sudo: required

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
  - docker build -t napnap75/rpi-gandi:latest .
  - docker images
  - docker run --rm -e API_KEY="$GANDI_API_KEY" -e GANDI_DOMAIN="$GANDI_DOMAIN" -e GANDI_HOST="$GANDI_HOST" napnap75/rpi-gandi:latest

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push napnap75/rpi-gandi:latest
